# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
"""PTODSL TileLib: ptodsl-native templates for ExpandTileOp (migration of tilelang-dsl).

Layers:
  - metadata     : TileSpec + dtypes + TemplateMetadata
  - author       : body ops (for_/get_lanes/make_mask/vlds/vadd/vsts), engine-routed
  - decorator    : @tile_template (registers a version + its metadata)
  - registry     : constraint/priority selection among registered versions
  - render       : render_best(op, target, specs) + CLI  (the ExpandTileOp seam)
  - templates/   : the ported per-arch template bodies
"""

from .author import (
    BarrierType,
    CmpMode,
    MaskPattern,
    PadValue,
    PostUpdate,
    PredicateDist,
    PredicatePart,
    Scalar,
    Tile,
    VStoreDist,
    VcvtPartMode,
    VcvtRoundMode,
    VcvtSatMode,
    addptr,
    bytewidth,
    cast_scalar,
    const_expr,
    constexpr,
    for_,
    get_lanes,
    get_op_attr,
    if_,
    inline_proc,
    mask_b16,
    mask_b8,
    mask_b32,
    make_mask,
    mem_bar,
    init_align,
    pbitcast,
    pdintlv_b8,
    pdintlv_b32,
    pand,
    pintlv_b16,
    pintlv_b32,
    plds,
    pset_b16,
    pset_b32,
    pnot,
    psts,
    punpack,
    pxor,
    scalar,
    static_range,
    vabs,
    vadd,
    vadds,
    vand,
    vbr,
    vbitcast,
    vcadd,
    vcmax,
    vcmin,
    vcvt,
    vcmp,
    vcmps,
    vdiv,
    vdintlv,
    vdup,
    vexp,
    vexpdif,
    vecscope,
    vlds,
    vlrelu,
    vmax,
    vmaxs,
    vmin,
    vmins,
    vmul,
    vmull,
    vmuls,
    vneg,
    vnot,
    vor,
    vrelu,
    vprelu,
    vsel,
    vshl,
    vshls,
    vshr,
    vshrs,
    vsqrt,
    vsts,
    vsub,
    vsubs,
    vtrc,
    vintlv,
    vstas,
    vstus,
    vxor,
    yield_,
)
from .constraints import (
    BLayout,
    SLayout,
    check_layout,
    check_memory_space,
    check_type,
    require_contiguous,
)
from .decorator import SpecializedTileTemplate, TileTemplate, tile_template
from .metadata import (
    ScalarSpec,
    ScalarType,
    TemplateMetadata,
    TileSpec,
    bf16,
    f16,
    f32,
    i8,
    i16,
    i32,
    i64,
    si8,
    si16,
    si32,
    ui8,
    ui16,
    ui32,
)
from .registry import (
    AmbiguousTemplate,
    NoMatchingTemplate,
    TileTemplateRegistry,
    default_registry,
    legal_candidates,
    register,
    select,
)
from .render import render_best, select_and_specialize

__all__ = [
    # authoring surface
    "Tile",
    "Scalar",
    "PostUpdate",
    "tile_template",
    "for_",
    "static_range",
    "if_",
    "yield_",
    "const_expr",
    "constexpr",
    "get_op_attr",
    "inline_proc",
    "vecscope",
    "get_lanes",
    "make_mask",
    "addptr",
    "scalar",
    "cast_scalar",
    "BarrierType",
    "CmpMode",
    "MaskPattern",
    "PadValue",
    "PredicateDist",
    "PredicatePart",
    "VStoreDist",
    "VcvtPartMode",
    "VcvtRoundMode",
    "VcvtSatMode",
    "mask_b16",
    "mask_b8",
    "mask_b32",
    "bytewidth",
    "mem_bar",
    "init_align",
    "pbitcast",
    "pdintlv_b8",
    "pdintlv_b32",
    "pand",
    "pintlv_b16",
    "pintlv_b32",
    "plds",
    "pset_b16",
    "pset_b32",
    "pnot",
    "psts",
    "punpack",
    "pxor",
    "vlds",
    "vadd",
    "vadds",
    "vsub",
    "vsubs",
    "vmul",
    "vmull",
    "vmuls",
    "vmax",
    "vmaxs",
    "vmin",
    "vmins",
    "vdiv",
    "vand",
    "vor",
    "vxor",
    "vshl",
    "vshls",
    "vshr",
    "vshrs",
    "vabs",
    "vneg",
    "vnot",
    "vrelu",
    "vlrelu",
    "vexp",
    "vexpdif",
    "vbr",
    "vsqrt",
    "vdup",
    "vcmax",
    "vcmin",
    "vcadd",
    "vcvt",
    "vcmp",
    "vcmps",
    "vtrc",
    "vintlv",
    "vdintlv",
    "vprelu",
    "vbitcast",
    "vsel",
    "vsts",
    "vstas",
    "vstus",
    # specs / metadata
    "TileSpec",
    "ScalarSpec",
    "ScalarType",
    "TemplateMetadata",
    "BLayout",
    "SLayout",
    "check_type",
    "check_memory_space",
    "check_layout",
    "require_contiguous",
    "f32",
    "f16",
    "bf16",
    "i32",
    "i64",
    "i16",
    "i8",
    "si32",
    "si16",
    "si8",
    "ui32",
    "ui16",
    "ui8",
    # descriptors
    "TileTemplate",
    "SpecializedTileTemplate",
    # registry / selection
    "TileTemplateRegistry",
    "default_registry",
    "legal_candidates",
    "register",
    "select",
    "NoMatchingTemplate",
    "AmbiguousTemplate",
    # rendering
    "render_best",
    "select_and_specialize",
]
