# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
"""A5 TileLib templates. Importing this package registers every template."""

from . import (  # noqa: F401  (import side effect: @tile_template registration)
    tabs,
    tadd,
    tadds,
    tand,
    tands,
    tcmp,
    tcmps,
    tcolargmax,
    tcolargmin,
    tcolexpand,
    tcolexpandadd,
    tcolexpandexpdif,
    tcolexpandmax,
    tcolexpandmin,
    tcolexpandmul,
    tcolexpandsub,
    tcolmax,
    tcolmin,
    tcolprod,
    tcolsum,
    tdiv,
    texpand,
    tfillpad,
    tfillpad_expand,
    tfillpad_inplace,
    tfmod,
    tfmods,
    tlrelu,
    tmax,
    tmaxs,
    tmin,
    tmins,
    tmov,
    tmul,
    tmuls,
    tneg,
    tnot,
    tor,
    tors,
    tpartadd,
    tpartmax,
    tpartmin,
    tpartmul,
    tprelu,
    trelu,
    trowexpand,
    trowexpandadd,
    trowexpandexpdif,
    trowexpandmax,
    trowexpandmin,
    trowexpandmul,
    trowexpandsub,
    trowmax,
    trowargmax,
    trowargmin,
    trowmin,
    trowprod,
    trowsum,
    trsqrt,
    tshl,
    tshls,
    tshr,
    tshrs,
    tsel,
    tsels,
    tsub,
    tsubs,
    trem,
    trems,
    txor,
    txors,
)
